apiVersion: batch/v1
kind: Job
metadata:
  name: submit-reaper
spec:
  parallelism: 1
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: submit-reaper
    spec:
      containers:
      - name: submit-container
        image: gradyfitz/submit-reaper
        env:
          - name: INITIAL_JOB_NUMBER
            value: "1"
      restartPolicy: OnFailure
      serviceAccountName: hub
