kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: submit-assignment-config
spec:
  # Use ephemeral storage since we don't need the shared drive to live.
  storageClassName: csi-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
